report result

diff --git a/.github/workflows/browser-js-staging.yml b/.github/workflows/browser-js-staging.yml
--- a/.github/workflows/browser-js-staging.yml
+++ b/.github/workflows/browser-js-staging.yml
@@ -14,6 +14,7 @@ jobs:
   e2e-tests:
     name: Run E2E tests
     runs-on: ubuntu-latest
+    continue-on-error: true
     strategy:
       matrix:
         node-version: [18.x]
@@ -45,9 +46,13 @@ jobs:
       - name: Test
         id: run-tests
         run: npm run -w=@sw-internal/e2e-js dev -- --project ${{ matrix.project }}
-        continue-on-error: true
         env:
           SW_TEST_CONFIG: ${{ secrets.STAGING_E2E_JS_SW_TEST_CONFIG }}
+      - name: Set job result output
+        if: always()
+        run: echo "::set-output name=e2e_test_result::$STATUS"
+        env:
+          STATUS: ${{ job.status }}
       - name: Report Result
         if: success() || failure()
         uses: ./.github/actions/report-test-result
@@ -59,12 +64,24 @@ jobs:
           influxdb-org: ${{ secrets.INFLUXDB_ORG }}
           influxdb-token: ${{ secrets.INFLUXDB_TOKEN }}
           influxdb-url: ${{ secrets.INFLUXDB_URL }}
+  report-results:
+    runs-on: ubuntu-latest
+    needs: e2e-tests
+    if: always()
+    steps:
+      - name: Check results of matrix jobs
+        run: |
+          failed_jobs=0
+          for job in ${{ toJson(needs.e2e-tests.results) }}; do
+            if [ ${{ job.conclusion }} != 'success' ]; then
+              echo "A job failed"
+              failed_jobs=$((failed_jobs + 1))
+            fi
+          done
 
-    # if: success() || failure()
-    # runs-on: ubuntu-latest
-    # needs: e2e-tests
-    # steps:
-    #   - name: Report Results
-    #     uses: actions/report-test-result@v1
-    #     with:
-    #       result: needs.e2e-tests.result
+          if [ $failed_jobs -ne 0 ]; then
+            echo "Failing the workflow because $failed_jobs jobs failed."
+            exit 1
+          else
+            echo "All jobs succeeded."
+          fi
